site_name: isq
site_author: Richard Schneider <makaretu@gmail.com>
markdown_extensions:
  - admonition
pages:
- Home: index.md
- Getting Started: gettingStarted.md
- Notation: notation.md
- Math: math.md
- Uncertainty: uncertainty.md
- Configuration:  pluggable.md
- Support: support.md
- Resources: resources.md
